export enum AuditAction {
  LOGIN = 'CONNEXION',
  LOGOUT = 'DÉCONNEXION',
  CREATE_PATIENT = 'CRÉATION_PATIENT',
  EDIT_PATIENT = 'MODIF_PATIENT',
  DELETE_PATIENT = 'SUPPRESSION_PATIENT',
  VIEW_PATIENT = 'CONSULTATION_PATIENT',
  CREATE_APPOINTMENT = 'CRÉATION_RDV',
  EDIT_APPOINTMENT = 'MODIF_RDV',
  DELETE_APPOINTMENT = 'SUPPRESSION_RDV',
  CREATE_CONSULTATION = 'CRÉATION_CONSULTATION',
  CREATE_PRESCRIPTION = 'CRÉATION_ORDONNANCE',
  EDIT_SETTINGS = 'MODIF_PARAMÈTRES',
  USER_MANAGEMENT = 'GESTION_UTILISATEURS',
  BILLING_ACTION = 'FACTURATION',
  CREATE_BILLING = 'CRÉATION_FACTURE',
  DELETE_BILLING = 'SUPPRESSION_FACTURE',
  SECURITY_ALERT = 'ALERTE_SÉCURITÉ'
}

export enum AuditCategory {
  SECURITY = 'SÉCURITÉ',
  MEDICAL = 'MÉDICAL',
  BILLING = 'FACTURATION',
  SYSTEM = 'SYSTÈME'
}

export interface AuditLog {
  id: string;
  timestamp: Date;
  userId: string;
  userName: string;
  userRole: string;
  action: AuditAction;
  category: AuditCategory;
  details: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
}

